# Generated by Django 6.0.2 on 2026-02-11 17:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('intervalo_doses_dias', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vacina',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='usuarios.perfildono')),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aplicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacinas_aplicadas', to='usuarios.perfilfuncionario')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_vacinas', to='clinica.pet')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='clinica.vacina')),
            ],
            options={
                'db_table': 'pet_vacina',
            },
        ),
    ]
